version: "3.8"

services:

  loyal_api:
    image: loyal:latest
    container_name: loyal_api
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@loyal_db:5432/${DATABASE_NAME}
    ports:
      - 8080:8080
    depends_on:
      - loyal_migrations
    networks:
      - loyal_network

  loyal_migrations:
    image: loyal:latest
    container_name: loyal_migrations
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@loyal_db:5432/${DATABASE_NAME}
    depends_on:
      - loyal_db
    command: sh -c "sleep 3 && alembic upgrade head"
    networks:
      - loyal_network

  loyal_db:
    image: postgres:13-alpine
    container_name: loyal_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - loyal_network

networks:
  loyal_network:
    name: loyal_network
